-- Script for creating Microsoft SQL Database, table and populating table

CREATE DATABASE [CIDR]  
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CIDR', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CIDR.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CIDR_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\CIDR_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [CIDR] SET COMPATIBILITY_LEVEL = 120
GO
ALTER DATABASE [CIDR] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CIDR] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CIDR] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CIDR] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CIDR] SET ARITHABORT OFF 
GO
ALTER DATABASE [CIDR] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CIDR] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CIDR] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [CIDR] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CIDR] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CIDR] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CIDR] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CIDR] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CIDR] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CIDR] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CIDR] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CIDR] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CIDR] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CIDR] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CIDR] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CIDR] SET  READ_WRITE 
GO
ALTER DATABASE [CIDR] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CIDR] SET  MULTI_USER 
GO
ALTER DATABASE [CIDR] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CIDR] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [CIDR] SET DELAYED_DURABILITY = DISABLED 
GO
USE [CIDR]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [CIDR] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

/*	Creating Table inside database, with primary key "ID" so it won't contain duplicates and values could be easily identified
	IPBlock contains the CIDR block
	Port column contains the specific port for each CIDR
	Allow column with values Yes/No (can be also boolean 1/0) specify if we are allowing a specific IP CIDR & Port in the system
*/

CREATE TABLE CIDR (
    ID int NOT NULL,
	IPBlock varchar(255),
    Port int,
    Allow varchar(255),
	PRIMARY KEY (ID)
);

GO
USE [CIDR]
GO

INSERT INTO [dbo].[CIDR]
           ([ID]
           ,[IPBlock]
           ,[Port]
           ,[Allow])
     VALUES
	 /*Allow all requests from 192.168.0.1/24 class on port 80/443 and deny port 21
	   Allow all requests from 10.0.0.60/24 class on port 22/445 except 1 IP inside this group 10.0.0.60/24
	   Allow only http requests from 82.16.24.3/32
	   Allow only http requests from 79.112.35.109/32 and blocks https requests
	 */
           (1,'192.168.0.1/24',80,'Yes'), 
		   (2,'192.168.0.1/24',443,'Yes'),
		   (3,'192.168.0.1/24',21,'No'),
		   (4,'10.0.0.1/23',22,'Yes'),
		   (5,'10.0.0.1/23',445,'Yes'),
		   (6,'10.0.0.60/32',22,'No'),
		   (7,'10.0.0.60/32',445,'No'),
		   (8,'82.16.24.3/32',80,'Yes'),
		   (9,'79.112.35.109/32',80,'No'),
		   (10,'79.112.35.109/32',443,'Yes')
GO

